import { defineNuxtModule, addPlugin, createResolver, addComponent, addTypeTemplate } from '@nuxt/kit'
import { defu } from 'defu'

// Re-export types for user convenience
export type {
  DocumentProperties,
  DocumentPropertiesOptions,
  ZoomLevel,
  ViewMode,
  ScrollMode,
  SearchMatch,
  PdfViewerControls,
} from './runtime/types'

// Toolbar configuration interface
export interface ToolbarOptions {
  /** Show sidebar toggle button */
  sidebar?: boolean
  /** Show page navigation (prev/next page buttons) */
  pageNavigation?: boolean
  /** Show zoom controls */
  zoom?: boolean
  /** Show search */
  search?: boolean
  /** Show rotate button */
  rotate?: boolean
  /** Show open file button */
  openFile?: boolean
  /** Show print button */
  print?: boolean
  /** Show download button */
  download?: boolean
  /** Show fullscreen button */
  fullscreen?: boolean
  /** Show theme toggle button */
  themeToggle?: boolean
  /** Show more options menu */
  moreOptions?: boolean
}

// Module options TypeScript interface definition
export interface ModuleOptions {
  /**
   * Toolbar configuration - control which buttons are visible
   */
  toolbar?: ToolbarOptions
}

// Default toolbar options
const defaultToolbar: Required<ToolbarOptions> = {
  sidebar: true,
  pageNavigation: true,
  zoom: true,
  search: true,
  rotate: true,
  openFile: false, // Disabled by default
  print: true,
  download: true,
  fullscreen: true,
  themeToggle: true,
  moreOptions: true,
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-pdf-kit',
    configKey: 'pdfKit',
    // Compatibility constraints
    compatibility: {
      // Supports Nuxt 3.x and 4.x
      nuxt: '>=3.0.0',
    },
  },
  // Default configuration options of the Nuxt module
  defaults: {
    toolbar: defaultToolbar,
  },
  // Module dependencies with proper configuration
  moduleDependencies: {
    '@nuxt/ui': {
      version: '>=3.0.0',
    },
    '@vueuse/nuxt': {
      version: '>=10.0.0',
    },
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    // Merge toolbar options with defaults using defu
    const toolbarConfig = defu(options.toolbar, defaultToolbar)

    // Expose options to runtime using defu to not overwrite user config
    nuxt.options.runtimeConfig.public.pdfKit = defu(
      nuxt.options.runtimeConfig.public.pdfKit as { toolbar?: ToolbarOptions } | undefined,
      { toolbar: toolbarConfig },
    )

    // Add plugin
    addPlugin(resolver.resolve('./runtime/plugin'))

    // Add components with client-only mode for SSR support
    addComponent({
      name: 'NuxtPdfKit',
      filePath: resolver.resolve('./runtime/components/NuxtPdfViewer.client.vue'),
      mode: 'client',
    })
    addComponent({
      name: 'NuxtPdfKitPage',
      filePath: resolver.resolve('./runtime/components/NuxtPdfPage.client.vue'),
      mode: 'client',
    })
    addComponent({
      name: 'NuxtPdfKitThumbnail',
      filePath: resolver.resolve('./runtime/components/NuxtPdfThumbnail.vue'),
    })
    addComponent({
      name: 'NuxtPdfKitThumbnails',
      filePath: resolver.resolve('./runtime/components/NuxtPdfThumbnails.client.vue'),
      mode: 'client',
    })

    // Add composables using addImports for explicit control (avoid duplicate from index.ts)
    const composables = [
      'usePdfKitDocument',
      'usePdfKitPageNavigation',
      'usePdfKitRotation',
      'usePdfKitSearch',
      'usePdfKitViewMode',
      'usePdfKitVirtualScroll',
      'usePdfKitZoom',
    ]

    for (const name of composables) {
      nuxt.hook('imports:extend', (imports) => {
        imports.push({
          name,
          from: resolver.resolve(`./runtime/composables/${name}`),
        })
      })
    }

    // Add type declarations for runtime config augmentation
    addTypeTemplate({
      filename: 'types/nuxt-pdf-kit.d.ts',
      getContents: () => `// Generated by nuxt-pdf-kit
import type { ToolbarOptions } from 'nuxt-pdf-kit'

interface PdfKitPublicRuntimeConfig {
  toolbar: Required<ToolbarOptions>
}

declare module 'nuxt/schema' {
  interface PublicRuntimeConfig {
    pdfKit: PdfKitPublicRuntimeConfig
  }
}

declare module '@nuxt/schema' {
  interface PublicRuntimeConfig {
    pdfKit: PdfKitPublicRuntimeConfig
  }
}

export {}
`,
    })

    // Automate transpilation so users don't have to do it manually
    nuxt.options.build.transpile.push('pdfjs-dist')

    // Vite optimization for pdfjs-dist
    nuxt.options.vite.optimizeDeps = nuxt.options.vite.optimizeDeps || {}
    nuxt.options.vite.optimizeDeps.include = nuxt.options.vite.optimizeDeps.include || []
    if (!nuxt.options.vite.optimizeDeps.include.includes('pdfjs-dist')) {
      nuxt.options.vite.optimizeDeps.include.push('pdfjs-dist')
    }

    // SSR handling
    nuxt.options.vite.ssr = nuxt.options.vite.ssr || {}
    nuxt.options.vite.ssr.noExternal = nuxt.options.vite.ssr.noExternal || []
  },
})
